export const CARD_ROYALTIES: {
  id: number;
  primary_royalty: number;
  secondary_royalty: number;
}[] = [
  { id: 1, primary_royalty: 0, secondary_royalty: 0 },
  { id: 2, primary_royalty: 0, secondary_royalty: 0 },
  { id: 3, primary_royalty: 0.8, secondary_royalty: 1 },
  { id: 4, primary_royalty: 0.8, secondary_royalty: 1 },
  { id: 5, primary_royalty: 0.8, secondary_royalty: 0.8 },
  { id: 6, primary_royalty: 0.8, secondary_royalty: 1 },
  { id: 7, primary_royalty: 0.7, secondary_royalty: 0.5 },
  { id: 8, primary_royalty: 0.5, secondary_royalty: 0.5 },
  { id: 9, primary_royalty: 0.8, secondary_royalty: 1 },
  { id: 10, primary_royalty: 0.5, secondary_royalty: 0.5 },
  { id: 11, primary_royalty: 0, secondary_royalty: 0.8 },
  { id: 12, primary_royalty: 0.5, secondary_royalty: 0.5 },
  { id: 13, primary_royalty: 0.931, secondary_royalty: 0.5 },
  { id: 14, primary_royalty: 0, secondary_royalty: 0.5 },
  { id: 15, primary_royalty: 0, secondary_royalty: 0 },
  { id: 16, primary_royalty: 0, secondary_royalty: 1 },
  { id: 17, primary_royalty: 0, secondary_royalty: 0.8 },
  { id: 18, primary_royalty: 0, secondary_royalty: 0.8 },
  { id: 19, primary_royalty: 0, secondary_royalty: 0.8 },
  { id: 20, primary_royalty: 0, secondary_royalty: 0.8 },
  { id: 21, primary_royalty: 0, secondary_royalty: 0.8 },
  { id: 22, primary_royalty: 0.8, secondary_royalty: 0.8 },
  { id: 23, primary_royalty: 0, secondary_royalty: 0 },
  { id: 24, primary_royalty: 0, secondary_royalty: 0.8 },
  { id: 25, primary_royalty: 1, secondary_royalty: 0.5 },
  { id: 26, primary_royalty: 0.8, secondary_royalty: 0.5 },
  { id: 27, primary_royalty: 0, secondary_royalty: 0.8 },
  { id: 28, primary_royalty: 0, secondary_royalty: 0.8 },
  { id: 29, primary_royalty: 0, secondary_royalty: 0.8 },
  { id: 30, primary_royalty: 0, secondary_royalty: 0 },
  { id: 31, primary_royalty: 0.8, secondary_royalty: 0.5 },
  { id: 32, primary_royalty: 0, secondary_royalty: 0.5 },
  { id: 33, primary_royalty: 1, secondary_royalty: 1 },
  { id: 34, primary_royalty: 0.8, secondary_royalty: 0.8 },
  { id: 35, primary_royalty: 0.75, secondary_royalty: 0.75 },
  { id: 36, primary_royalty: 0.8, secondary_royalty: 0.8 },
  { id: 37, primary_royalty: 0.5, secondary_royalty: 0.5 },
  { id: 38, primary_royalty: 0, secondary_royalty: 0.8 },
  { id: 39, primary_royalty: 0, secondary_royalty: 0.8 },
  { id: 40, primary_royalty: 0, secondary_royalty: 0.8 },
  { id: 41, primary_royalty: 0, secondary_royalty: 0 },
  { id: 42, primary_royalty: 0, secondary_royalty: 0 },
  { id: 43, primary_royalty: 0.9, secondary_royalty: 0.5 },
  { id: 44, primary_royalty: 0.8, secondary_royalty: 0.8 },
];
